import type {Metadata} from "next";
import {Roboto} from "next/font/google";

import "./globals.css";

const roboto = Roboto({
    subsets: ["cyrillic", "latin"],
    weight: ["100", "300", "400", "500", "700", "900"],
    style: ["normal"],
    variable: "--font-roboto"
});


export const metadata: Metadata = {
    title: "RICC",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={roboto.className}>
        <body>
        <div className="container mx-auto my-0 grow pb-8">
            {children}
        </div>
        </body>
        </html>
    );
}
