import i18nConfig from "../../../i18nConfig";
import "./globals.css";
import initServerTranslations from "@/app/i18n";
import { Footer } from "@/components/Footer/Footer";
import { Header } from "@/components/Header/Header";
import Providers from "@/components/Providers/Providers";
import ServerErrorDialog from "@/components/ServerErrorDialog/ServerErrorDialog";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["cyrillic", "latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal"],
  variable: "--font-roboto"
});

export const metadata: Metadata = {
  title: "RICC",
  description: "Generated by create next app"
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { resources } = await initServerTranslations(locale);
  return (
    <html
      lang={locale}
      className={roboto.className}
    >
      <body>
        <Providers
          locale={locale}
          resources={resources}
        >
          <Header />
          <div className='container'>{children}</div>
          <Footer />
          <ServerErrorDialog />
        </Providers>
      </body>
    </html>
  );
}
